package com.newax.aegis.engine.apps

enum class AppCapability {
    OPEN_APP, SEARCH, SEND_TEXT, SEND_FILE, CALL, VIDEO_CALL,
    PLAY_MEDIA, PAUSE, NAVIGATE, CREATE_NOTE, CREATE_EVENT, OPEN_URL,
    TAKE_PHOTO, SCAN_DOCUMENT, UPLOAD, DOWNLOAD, SHARE_TEXT, SHARE_MEDIA,
    PRINT, EDIT, DELETE, SAVE, WEB_SEARCH, SEARCH_MUSIC,
    MESSAGE_WORKFLOW, OPEN_CONTACT_LINK
}
