package com.newax.aegis.db

import androidx.room.Room
import androidx.sqlite.driver.NativeSQLiteDriver
import platform.Foundation.NSApplicationSupportDirectory
import platform.Foundation.NSSearchPathForDirectoriesInDomains
import platform.Foundation.NSUserDomainMask

/**
 * Apple (macOS + iOS) construction seam for the Newax memory fabric — the
 * "native driver" of the ARCHITECTURE.md platform matrix. The database is
 * backed by the OS-provided SQLite (libsqlite3) via [NativeSQLiteDriver]
 * from androidx.sqlite:sqlite-framework, instead of the bundled SQLite the
 * desktop uses or the SQLCipher that Android uses.
 *
 * The schema, DAOs, and the eighteen migrations are the same shared commonMain
 * surface as every other platform: version 19 with the identical migration
 * chain, so a database created on Android, Windows, or macOS opens unchanged
 * here. The `actual object NewaxDatabaseConstructor` the commonMain
 * `@ConstructedBy(NewaxDatabaseConstructor::class)` expects is generated by
 * Room's KSP run per native target (Room KMP's
 * findDatabaseConstructorAndInitDatabaseImpl), exactly as on desktop.
 */

/** Opens the Newax database at the platform default location (Application Support). */
fun getNewaxDatabase(): NewaxDatabase = getNewaxDatabase(defaultDatabasePath())

/** Opens the Newax database at an explicit path (tests, custom locations). */
fun getNewaxDatabase(path: String): NewaxDatabase =
    Room.databaseBuilder<NewaxDatabase>(
        name = path,
    )
        .setDriver(NativeSQLiteDriver())
        .addMigrations(
            NewaxDatabase.MIGRATION_1_2,
            NewaxDatabase.MIGRATION_2_3,
            NewaxDatabase.MIGRATION_3_4,
            NewaxDatabase.MIGRATION_4_5,
            NewaxDatabase.MIGRATION_5_6,
            NewaxDatabase.MIGRATION_6_7,
            NewaxDatabase.MIGRATION_7_8,
            NewaxDatabase.MIGRATION_8_9,
            NewaxDatabase.MIGRATION_9_10,
            NewaxDatabase.MIGRATION_10_11,
            NewaxDatabase.MIGRATION_11_12,
            NewaxDatabase.MIGRATION_12_13,
            NewaxDatabase.MIGRATION_13_14,
            NewaxDatabase.MIGRATION_14_15,
            NewaxDatabase.MIGRATION_15_16,
            NewaxDatabase.MIGRATION_16_17,
            NewaxDatabase.MIGRATION_17_18,
            NewaxDatabase.MIGRATION_18_19
        )
        .build()

private fun defaultDatabasePath(): String {
    val dirs = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, true)
    val base = dirs.firstOrNull()
        ?: error("Cannot resolve the Application Support directory on this Apple platform")
    return "$base/aegis.db"
}
